config/routes.rb
Rails.application.routes.draw do
  resources :task_contents
  resources :labels
  resources :deliveries
  resources :tasks
  resources :users
  root 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/label.rb
class Label < ApplicationRecord
    validates :name, presence: true
    
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  
  def index
    @label = Label.all.order(created_at: :desc)
  end

  def show
  end  
  
  def new
    @label = Label.new
  end
  
  def create
    @label = Label.new(label_params)
    if @label.save
      flash[:notice] = "Succeeded !"
      redirect_to("/labels")
    else
      render("labels/new")
    end
  end
  
  def edit
  end
  
  def update
    #@label.name = params[:name]
    #if @label.save
    if @label.update(label_params)
      flash[:notice] = "Succeeded !"
      redirect_to("/labels")
    else
      render("labels/edit")
    end
  end

  def destroy
    @label.destroy
    flash[:notice] = "Succeeded !"
    redirect_to("/labels")
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find_by(id: params[:id])
    end
    
      # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end
  
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% label.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/labels/edit.html.erb
<h1>Edit</h1>

<%= render 'form', label: @label %>

<p><%= link_to("Back", labels_path) %></p>

app/views/labels/index.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<h1>Labels</h1>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @label.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Delete',label, method: "delete", data: { confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to("New name", new_label_path) %>

app/views/labels/new.html.erb
<h1>New name</h1>

<%= render 'form', label: @label  %>

<p><%= link_to("Back", labels_path) %></p>

app/views/labels/show.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>
 
<strong>Label name:</strong>
<%= @label.name  %>
  
<p><%= link_to("Edit", edit_label_path(@label)) %></p>
<p><%= link_to("Delete", @label, method: "delete", data: { confirm: "Are you sure?"}) %></p>
<p><%= link_to("Back", labels_path) %></p>