config/routes.rb
Rails.application.routes.draw do
  resources :task_contents
  resources :labels
  resources :deliveries
  resources :tasks
  resources :users
  root 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task_content.rb
class TaskContent < ApplicationRecord
    validates :task_content, {presence: true}
    validates :desired_completion_date, {presence: true}
end

app/controllers/task_contents_controller.rb
class TaskContentsController < ApplicationController
  before_action :set_task_content, only: [:show, :edit, :update, :destroy]

  # GET /task_contents
  # GET /task_contents.json
  def index
    @task_contents = TaskContent.all.order(created_at: :desc)
  end

  # GET /task_contents/1
  # GET /task_contents/1.json
  def show
  end

  # GET /task_contents/new
  def new
    @task_content = TaskContent.new
  end

  # GET /task_contents/1/edit
  def edit
  end

  # POST /task_contents
  # POST /task_contents.json
  def create
    @task_content = TaskContent.new(task_content_params)

    respond_to do |format|
      if @task_content.save
        format.html { redirect_to @task_content, notice: 'Task content was successfully created.' }
        format.json { render :show, status: :created, location: @task_content }
      else
        format.html { render :new }
        format.json { render json: @task_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_contents/1
  # PATCH/PUT /task_contents/1.json
  def update
    respond_to do |format|
      if @task_content.update(task_content_params)
        format.html { redirect_to @task_content, notice: 'Task content was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_content }
      else
        format.html { render :edit }
        format.json { render json: @task_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_contents/1
  # DELETE /task_contents/1.json
  def destroy
    @task_content.destroy
    respond_to do |format|
      format.html { redirect_to task_contents_url, notice: 'Task content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_content
      @task_content = TaskContent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_content_params
      params.require(:task_content).permit(:task_content, :desired_completion_date)
    end
end

app/helpers/task_contents_helper.rb
module TaskContentsHelper
end

app/views/task_contents/_form.html.erb
<%= form_with(model: task_content, local: true) do |form| %>
  <% if task_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_content.errors.count, "error") %> prohibited this task_content from being saved:</h2>

      <ul>
        <% task_content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_content %>
    <%= form.text_area :task_content %>
  </div>

  <div class="field">
    <%= form.label :desired_completion_date %>
    <%= form.datetime_select :desired_completion_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_contents/edit.html.erb
<h1>Editing Task Content</h1>

<%= render 'form', task_content: @task_content %>

<%= link_to 'Show', @task_content %> |
<%= link_to 'Back', task_contents_path %>

app/views/task_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Contents</h1>

<table>
  <thead>
    <tr>
      <th>Task content</th>
      <th>Desired completion date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_contents.each do |task_content| %>
      <tr>
        <td><%= task_content.task_content %></td>
        <td><%= task_content.desired_completion_date %></td>
        <td><%= link_to 'Show', task_content %></td>
        <td><%= link_to 'Edit', edit_task_content_path(task_content) %></td>
        <td><%= link_to 'Destroy', task_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Content', new_task_content_path %>

app/views/task_contents/new.html.erb
<h1>New Task Content</h1>

<%= render 'form', task_content: @task_content %>

<%= link_to 'Back', task_contents_path %>

app/views/task_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task content:</strong>
  <%= @task_content.task_content %>
</p>

<p>
  <strong>Desired completion date:</strong>
  <%= @task_content.desired_completion_date %>
</p>

<%= link_to 'Edit', edit_task_content_path(@task_content) %> |
<%= link_to 'Back', task_contents_path %>